name: Update Windows Versions and CVE Mappings

on:
  schedule:
    - cron: '0 0 15 * *' # Run at midnight UTC on the 15th of each month
  push:
    branches:
      - main
    paths:
      - 'generate_os_cve_data.ps1'
      - 'kb_cve_data.csv' # Adjust if your data source has a different name
  workflow_dispatch: # Allow manual triggering

jobs:
  update-json:
    runs-on: windows-latest # Use Windows runner for PowerShell compatibility

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up PowerShell
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x' # Optional, if your script uses .NET dependencies

    - name: Run PowerShell script
      shell: pwsh
      run: |
        ./generate_os_cve_data.ps1

    - name: Commit and push changes
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git remote set-url origin https://x-access-token:$GH_TOKEN@github.com/ZentrixLabs/windows-version-feed.git
        git add windows-versions.json CVE_KB_Mapping_*.json kb_cve_data.csv
        git diff --staged --quiet || git commit -m "Update windows-versions.json, CVE_KB_Mapping, and kb_cve_data for $((Get-Date -Format 'yyyy-MMMM'))"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
