name: Update Windows Versions and CVE Mappings

on:
  schedule:
    - cron: '0 0 * * *' # Every day at 00:00 UTC
  push:
    branches:
      - main
    paths:
      - 'generate_os_cve_data.ps1'
      - 'kb_cve_data.csv'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-json:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Full history for accurate commits

      - name: Run PowerShell script
        shell: pwsh
        run: |
          try {
            ./generate_os_cve_data.ps1
          } catch {
            Write-Error "Script failed: $_"
            exit 1
          }

      - name: Commit and push changes
        shell: bash
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          files_to_add=""
          test -f windows-versions.json && files_to_add="$files_to_add windows-versions.json"
          test -f windows-versions-current.json && files_to_add="$files_to_add windows-versions-current.json"
          test -f kb_cve_data.csv && files_to_add="$files_to_add kb_cve_data.csv"

          for file in CVE_KB_Mapping_*.json cvrf_mapping_debug_*.txt; do
            test -f "$file" && files_to_add="$files_to_add $file"
          done

          if [ -n "$files_to_add" ]; then
            git add $files_to_add
            git diff --staged --quiet || git commit -m "Update CVE-to-KB mappings for $(date +'%Y-%m-%d')"
            git push
          else
            echo "No files to commit."
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
