name: Update Windows Versions and CVE Mappings

on:
  schedule:
    - cron: '0 0 * * 3'  # Every Wednesday at 00:00 UTC
  push:
    branches:
      - main
    paths:
      - 'generate_os_cve_data.ps1'
      - 'kb_cve_data.csv'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-json:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up PowerShell
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Run PowerShell script
      shell: pwsh
      run: |
        ./generate_os_cve_data.ps1

    - name: Commit and push changes
      shell: bash
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add windows-versions.json CVE_KB_Mapping_*.json kb_cve_data.csv
        git diff --staged --quiet || git commit -m "Update windows-versions.json, CVE_KB_Mapping, and kb_cve_data for $(date +'%Y-%B')"
        git push
